services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" # Local config
    expose:
      - "${BACKEND_EXPOSE_PORT}"
    volumes:
      - pycoustics_recordings:/app/recordings_data
      - pycoustics_db:/app/data
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "${API_URL}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=${API_URL}
        - WS_URL=${WS_URL}
    ports:
      - "${FRONTEND_PORT}:80" # Local config
    expose:
      - "${FRONTEND_EXPOSE_PORT}"
    depends_on:
      - backend

volumes:
  pycoustics_recordings:
  pycoustics_db:
